services:
  app:
    build: ./docker/app
    ports:
      - 8000:8000
    volumes:
      - ./code:/app
    working_dir: /app
  database:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always